apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: echo-service-with-mongo
  name: echo-service-with-mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-service-with-mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo-service-with-mongo
    spec:
      containers:
      - name: echo-service-with-mongo
        image: echo-service-with-mongo
        ports:
        - containerPort: 3000
        env:
          - name: BINDING
            valueFrom:
              secretKeyRef:
                name: binding-db-mongo-swp
                key: binding
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service-with-mongo-api
spec:
  selector:
    app: echo-service-with-mongo
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
