apiVersion: v1
kind: Namespace
metadata:
  name: swp-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service-with-mongo
  namespace: swp-ns
  labels: 
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: echo-service-with-mongo-container
        image: echo-service-with-mongo-image
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: BINDING
            valueFrom:
              secretKeyRef:
                name: binding-db-mongo-swp
                key: binding
        envFrom:
          - configMapRef:
              name: echo-service-with-mongo-config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service-with-mongo-api
  namespace: swp-ns
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-service-with-mongo-config
  namespace: swp-ns
data:
  TESTVAR: myvar