FROM registry.access.redhat.com/ub18/nodejs-12 as base

FROM base as builder

# create app directory
WORKDIR /opt/app-root/src

# install app deps
COPY package*.json ./

RUN npm ci

COPY public public
COPY src src

RUN npm run build

COPY --from=builder /opt/app-root/src/build build

RUN npm ci --only=production

COPY server.js .

ENV NODE_ENV=production
ENV PORT=3000


EXPOSE 3000

CMD [ "node", "server.js" ]